### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IanEdington** [generoi/packagist#1]
Hi @oxyc,
Thank you for sharing this code! I'm planning on using the process you've outlined.

Can you provide a license on this codebase so it's clear that it's open and free software? MIT is a great license that many projects like this use.

Regards,
Ian

**Comment by oxyc** [comment]
Sure, I’ll add a MIT license later this week. Feel free to do whatever with it before that

**Comment by IanEdington** [comment]
Awesome! Thanks

**Comment by oxyc** [comment]
Done https://github.com/generoi/packagist/commit/85f80a8f2934aecc25a5c98bec01a81578564c4e
